### ISSUE TITLE
Test suite fails to build

### ISSUE THREAD

**Issue by mihaimaruseac** [roman/Haskell-teardown#1]
On Stackage nightly, missing entry in package.yaml file. Full log:

```
Preprocessing test suite 'teardown-test' for teardown-0.1.0.0...
[1 of 1] Compiling Main             ( test/TestSuite.hs, dist/build/teardown-test/teardown-test-tmp/Main.o )
Linking dist/build/teardown-test/teardown-test ...
> /tmp/stackage-build13/teardown-0.1.0.0$ dist/build/teardown-doctest/teardown-doctest

/tmp/stackage-build13/teardown-0.1.0.0/src/Control/Teardown/Internal/Types.hs:6:1: error:
    Failed to load interface for ‘Protolude’
    It is a member of the hidden package ‘protolude-0.1.10’.
    Use -v to see a list of the files searched for.
```

**Comment by mihaimaruseac** [comment]
Not opening a new issue, but benchmarks fail to build too, most likely a similar reason

```
Preprocessing benchmark 'teardown-benchmark' for teardown-0.1.0.0...
[1 of 1] Compiling Main             ( benchmark/Main.hs, dist/build/teardown-benchmark/teardown-benchmark-tmp/Main.o )

benchmark/Main.hs:6:1: error:
    Failed to load interface for ‘Lib’
    it is a hidden module in the package ‘termcolor-0.2.0.0’
    Use -v to see a list of the files searched for.
```

**Comment by roman** [comment]
Hey @mihaimaruseac,

Thanks for letting me know, in all honesty the benchmark is from a generated scaffolding, haven't removed it because I might need it, the test should run though, I'll investigate and fix. Thanks for letting me know.

**Comment by roman** [comment]
Hi @mihaimaruseac,

I've fixed the benchmark situation (actually created one), regarding the testsuite, for some reason I' not able to replicate this issue ¿? can you give me the specs to try to replicate this so that I can add it to the CI tests?

**Comment by mihaimaruseac** [comment]
Hi @roman 

Sorry, I was away with work and trip and only now managed to look into it. I checked again and the tests are still failing, same error.

You can test if you have Docker:

```
docker pull snoyberg/stackage
```

https://hub.docker.com/r/snoyberg/stackage/

**Comment by roman** [comment]
Hi @mihaimaruseac,

Thank you very much for keeping the conversation going, no worries about the non responsiveness, I'm quite busy myself too so it is ok if this take a bit more of time, hopefully you don't mind as much. 

I'm going through the documentation of [stackage/MAINTAINERS.md](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package) and through the [image's README in the docker site](https://hub.docker.com/r/snoyberg/stackage/) but I'm not able to figure out how to use this docker image to replicate the error you are mentioning

Can you provide me with steps (or better, a script) to run the tests as you are running them? Thanks  for your time and efforts.

**Comment by mihaimaruseac** [comment]
Hi.

Sorry, I have been away until now. Seems that the issue is now solved so I'll close this.

On the other hand, we cannot include it in nightly as protolude has not been updated to work with GHC-8.2.1. This requires no work from you, once protolude is updated your package will also be included.

Sorry again for not being able to respond in a timely fashion.
